Fix spurious SHLVL variable assignment by fenv.
oh-my-fish/plugin-foreign-env pull request #19
Opened 2019-01-15 02:54 UTC by edlanglois

Originally, the 2nd `env` call was made within one additional bash subshell
causing the SHLVL variable to differ and therefore be assigned by fenv.

In fish 3.0 this resulted in a warning message because SHLVL is read only.

2019-01-15 03:16 UTC, edlanglois commented
Correction: The SHLVL warning I encountered seems to have been triggered by the update to bash 5.0 rather than the update to fish 3.0. I don't have a fully understanding of the issues but possibly the latest version of bash increments SHLVL for certain subshells when past versions did not.

I don't know if that makes this a bash issue or not, but either way this change solves the problem.

Example invocation before the change in this commit:
```fish
> fenv true
set: Tried to change the read-only variable “SHLVL”
```

2019-01-15 19:01 UTC, scorphus requested changes
Awesome, @edlanglois! Thanks for catching it and creating a pull request 👍 

After #18 was merged, the changes introduced by your PR conflict with current `master`. Can you please fix them?

2019-01-15 20:04 UTC, edlanglois commented
Done

2019-01-16 09:42 UTC, scorphus approved these changes
Thanks, @edlanglois!

2019-01-16 09:46 UTC, scorphus commented
LGTM

Dear @oh-my-fish/core, squash and merge at your earliest convenience 😉

2019-01-16 16:15 UTC, sagebind approved these changes

2019-01-16 16:16 UTC, merged

2020-02-26 14:24 UTC, dansanduleac commented
I still get the same error running fish installed from nix, specifically when sourcing the nix per-user profile at `~/.nix-profile/etc/profile.d/nix.sh` with `fenv`.

I've added some debug logging in `fenv.parse.diff.fish` to showcase what changes:
```
Setting: NIX_SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt
Setting: PATH=/Users/dansanduleac/.nix-profile/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
Setting: _=/Users/dansanduleac/.nix-profile/bin/env
set: Tried to change the read-only variable “_”
```